### PR TITLE
Gui polygon robot support

### PR DESCRIPTION
**Pull request by etsardou**
Full support of polygon robots implemented. Closing #132 and #135, as they are resolved in the current pull request.

### CODE REVIEW

**Comment by trainman419** [comment]
I'm having trouble building this:

```
/Users/hendrix/hydro/catkin_ws/src/stdr_simulator/stdr_gui/include/stdr_gui/stdr_robot_creator/stdr_robot_footprint_loader.h:25:10: fatal error: 
      'ui_robotFootprint.h' file not found
#include "ui_robotFootprint.h"
```

**Comment by trainman419** [comment]
It builds for me now. I touched the CMakeLists.txt, and then it built properly. My best guess is that cmake was caching the list of .ui files to build into headers, and didn't notice that a new file was added.

**Comment by trainman419** [comment]
This works wonderfully for my robot.
:+1:

**Comment by etsardou** [comment]
Yea, sometimes you just have to erase the /devel and /build folders in order to perform a clean build ;) Glad everything works for you too!

**Comment by trainman419** [comment]
It looks like using `file(GLOB ...)` to find source files probably causing this. The recommended approach appears to be listing every file: http://stackoverflow.com/questions/10914607/how-to-collect-source-files-with-cmake-without-globbing

**Comment by etsardou** [comment]
Just saw I forgot to declare the new source file in the makefile :/ Check the last commit. This could be the culprit. We'll check the GLOB as well.

**Comment by trainman419** [comment]
I fixed the globbing of ui files that was causing my issue in #137

**Pull request merged**
