### PR TITLE
Omni motion ctrl capability

### PR DESCRIPTION
**Pull request by oscar-lima**
Provides with omni-directional motion control capability to the simulator, perhaps you should not merge directly but integrate into the code by doing some polymorphism, not sure about how you would like to integrate it.

todo : mean error and std deviation harcoded at 0.0, 0.0 at the moment, later on needs to be read from yaml file, also gui in qt shows currently only speed on x and theta, it should show y as well now.

Thanks!

Oscar

### CODE REVIEW

**Comment by czalidis** [comment]
Hi Oscar, thanks for the contribution. Yes, as you said this pull request can not be merged, it has some serious issues. @oscar-lima I don't know if you have the time and you are willing to fix any of those issues, but I am going to list a few of them.
- You just replaced the `ideal_motion_controller` (which is the only one available currently) with the `omni_motion_controller`. Obviously, they should exist side by side.
- Any new motion controller should inherit from the `MotionController` class, which is the base class for all motion controllers.
- The `CMakeLists.txt` file should be as general as possible without being tied to specific compiler or compiler version. Maybe there is a way to avoid those special compiler flags. (This is mostly affecting packaging into binary distributions, I am not sure how big of a problem is though) 
- Better use the `geometry_msgs/Pose2D` as a pose struct and not implement a custom one which is very similar.
- Right now, the selection of the motion controller for each robot is hardcoded ([stdr_robot.cpp:155](https://github.com/stdr-simulator-ros-pkg/stdr_simulator/blob/hydro-devel/stdr_robot/src/stdr_robot.cpp#L155-L156)). That, should obviously change so the user can define witch controller wants to use.
- The gui only shows `x` and `theta` speeds as you mentioned, obviously `y` should be also considered.
- Try to follow the coding standards. We try to [ROS's coding style](http://wiki.ros.org/CppStyleGuide), with the exception that for the private/protected members of a class an underscore is leading the name.

That's a few things that I noticed over a quick glance to your commits. Currently, I don't have the time to look deeper in this PR, maybe I will have some time to spare in a week or two. If you have the time to look into my comments and fix some of the issues, please let me know. There is a possibility that I can help you and do an initial iteration myself in 2 weeks or so. Of course, if someone else is also interested in contributing to this PR, he/she is welcome!

**Comment by etsardou** [comment]
Hey Oscar, thanks for the pull request! I agree with what Chris said. I'll try to correct these issues in the next days. If you are working (or you want to work) on them, just say so in order to coordinate ;)

PS. Actually I'll create a new branch to incorporate your changes as it will be easier than trying to invert the `ideal_motion_controller` code. This will help with the code abstraction as well.

**Comment by czalidis** [comment]
@etsardou great! I would strongly recommend, to anyone who wants to contribute, to start a new pull request, based on this PR and my comments.

Just to let you know, Hydro is approaching EOL and there will be a final sync for binary packages soon. It would be nice if we could manage to do our final release for Hydro with that feature included! Let me know about your plans, to schedule the next release.

**Comment by etsardou** [comment]
Ok! Though if the motion controller is abstracted several changes must be performed in the `stdr_robot`, `stdr_parser`, `stdr_gui`. Let's hope the changes won't take long!

**Comment by oscar-lima** [comment]
Many thanks! as you might already noticed I am busy at the moment, also I spend some time to get familiar with stdr and for the contribution as well, but you guys are doing some awesome work! thanks : ) . Particularly I am using stdr for the KUKA youbot so i needed omni controller and I had some homeworks from school that fitted just perfectly for doing this particular contribution

**Comment by etsardou** [comment]
Great! When you have time check your code with this pull request https://github.com/stdr-simulator-ros-pkg/stdr_simulator/pull/170 and give us some feedback to merge it. Also it would be excellent to create a tutorial in our ROS wiki page to describe your work involving the youbot / stdr integration (http://wiki.ros.org/stdr_simulator/Tutorials).

**Comment by czalidis** [comment]
I am closing this PR, in favor of #170.

**Pull request closed without merging**
