### PR TITLE
Add support for non-circular robots

### PR DESCRIPTION
**Pull request by trainman419**
This adds support for parsing footprints, uses footprint points if available in the robot model, and rotates the footprint during collision checking, so that collision checks work properly.

This exposes an existing bug where map points that lie between footprint points are not collision-checked. This means that the robot can drive "onto" the end of a wall and become stuck on the wall in certain circumstances.

### CODE REVIEW

**Comment by czalidis** [comment]
Thanks for the pull request, we are going to review it later today. It seems great!

Just have in mind that we indent to completely change our collision checking infrastructure, as of next release. Probably, we are going to use some kind of lightweight physics engine to perform collision checking.  If you are interested, we would be happy to listen your thoughts on an upcoming topic [here](https://groups.google.com/forum/#!forum/stdr-simulator).

That been said, I am not sure if we are going to merge this PR immediately or start redesigning the collision checking infrastructure. The bug you described was the main reason why we didn't implement that functionality at the first place.

**Comment by czalidis** [comment]
@trainman419  we are going to fix the bug you mentioned and merge this PR in the near future. This, is a temporary fix, until a more sophisticated collision checking infrastructure is deployed.

**Comment by trainman419** [comment]
I'm willing to live with the collision-checking bug; the existing behavior works most of the time. I brought it up in the interest of full disclosure; it's better to know about bugs than not.

**Comment by etsardou** [comment]
Hey there! Thanx for the contribution :) Since this bug can be easily solved we will solve it before the merge. Does this affect you in any way? You continue the work in this branch?

**Comment by trainman419** [comment]
Nope; this isn't blocking my work. Thanks!

**Comment by etsardou** [comment]
Will be included in #136. Thanks @trainman419 for the contribution!

**Pull request closed without merging**
